{{- if .Values.configMap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "viaroute-app.fullname" . }}-config
  labels:
    {{- include "viaroute-app.labels" . | nindent 4 }}
data:
  NODE_ENV: {{ .Values.app.env.NODE_ENV | quote }}
  PORT: {{ .Values.app.env.PORT | quote }}
  FRONTEND_URL: {{ .Values.app.env.FRONTEND_URL | quote }}
  DB_HOST: {{ .Values.database.host | quote }}
  DB_PORT: {{ .Values.database.port | quote }}
  DB_NAME: {{ .Values.database.name | quote }}
{{- end }}

