{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "viaroute-app.fullname" . }}-db-secret
  labels:
    {{- include "viaroute-app.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.postgresql.auth.username | default "postgres" | b64enc }}
  password: {{ .Values.secrets.databasePassword | default .Values.postgresql.auth.postgresPassword | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "viaroute-app.fullname" . }}-auth-secret
  labels:
    {{- include "viaroute-app.labels" . | nindent 4 }}
type: Opaque
data:
  domain: {{ .Values.secrets.auth0Domain | b64enc }}
  audience: {{ .Values.secrets.auth0Audience | b64enc }}
  jwtSecret: {{ .Values.secrets.jwtSecret | default "changeme" | b64enc }}
{{- end }}

